### ISSUE TITLE
state_id type inconsistency

### ISSUE THREAD

**Issue by zaidhuda** [lomotech/jajahan#7]
```
'state_id' => '09' // padded number as string
'state_id' => '2' // number as string
'state_id' => 1 // number as int
```
Is there any reason for the inconsistency?

**Comment by nasrulhazim** [comment]
@lomotech - need assistance on this issue?

**Comment by lomotech** [comment]
@nasrulhazim i think this issue is resolved. but not closed. @hudadiaz refer to district file rite?

ps. im working on restructure whole code. can see it at dev branch.
